spring:
  # Настройки базы данных PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/librarydb
    username: postgres
    password: postgres
  # JPA/Hibernate настройки
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # Настройки Spring Data REST
  data:
    rest:
      base-path: /api
      default-page-size: 20
      max-page-size: 100
      return-body-on-create: true
      return-body-on-update: true

# Настройки логирования
logging:
  level:
    org:
      springframework:
        data: INFO
        web: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      gualsh:
        demo:
          spdrest: DEBUG

# Настройки сервера
server:
  port: 8080
