# Настройки базы данных
spring:
  datasource:
    url: jdbc:h2:mem:librarydb
    driverClassName: org.h2.Driver
    username: sa
    password:

  # Настройки H2 консоли (доступна по адресу http://localhost:8080/h2-console)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA/Hibernate настройки
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Настройки Spring Data REST
  data:
    rest:
      base-path: /api
      default-page-size: 20
      max-page-size: 100
      return-body-on-create: true
      return-body-on-update: true

# Настройки логирования
logging:
  level:
    org.springframework.data: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.gualsh.demo.spdrest: DEBUG

# Настройки сервера
server:
  port: 8080
