version: '3.8'

services:
  app:
    image: jib-gradle-app:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/jib_db
      - SPRING_DATASOURCE_USERNAME=jib_user
      - SPRING_DATASOURCE_PASSWORD=jib_password
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: jib_db
      POSTGRES_USER: jib_user
      POSTGRES_PASSWORD: jib_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jib_user -d jib_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: