spring:
  # Spring Batch
  batch:
    job:
      enabled: false # Отключаю автоматический запуск Job-ов во время старта приложения

  # Spring shell
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

  # Mongo datasource
  data:
    mongodb:
      host: localhost
      port: 8099
      database: mdb

  # H2 datasource
  datasource:
    url: jdbc:h2:mem:h2db
    driver-class-name: org.h2.Driver
    username: root
    password: #root
  h2:
    console.enabled: true

  # Sql
  sql:
    init:
      mode: never

  # Конфигурация второго источника данных - PostgreSQL
  target-datasource:
    url: jdbc:postgresql://localhost:5432/target_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # Jpa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

# Embedded Mongo server
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

# MongoDB migration
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
