version: '3'

services:

  primary-db:
    image: postgres:14
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  secondary-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: users
      #MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"