server:
  port: 8080

spring:
  application:
    name: micrometer-demo

# Конфигурация Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Экспозиция всех эндпоинтов для демонстрации
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0  # Для демонстрации используем 100% сэмплирование
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true  # Включаем гистограммы для HTTP-запросов
      percentiles:
        http.server.requests: 0.5, 0.75, 0.95, 0.99  # Настраиваем процентили
    enable:
      jvm: true  # Включаем JVM-метрики
      process: true  # Включаем метрики процесса
      system: true  # Включаем системные метрики
      tomcat: true  # Включаем метрики Tomcat
      logback: true  # Включаем метрики логирования
  zipkin: # Настройки для Zipkin
    tracing:
      endpoint: http://localhost:9411/api/v2/spans