spring:
  data:
    # todo mongo section
    mongodb:
      port: 0 # todo when flapdoodle using
      database: company # todo database for use


# todo flapdoodle(встроенная Mongo) properties
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

# todo mongock section
mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean" # todo включаем при использовании spring-shell
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog # todo где классы наката лежат
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
