# Конфигурация Spring Boot приложения для демонстрации @HttpExchange
server:
  port: 8080

spring:
  application:
    name: httpe-demo

  # Конфигурация Jackson для JSON сериализации
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false

  # Конфигурация WebFlux
  webflux:
    base-path: /api

# Настройки для внешних API
external-apis:
  # JSONPlaceholder - бесплатный API для тестирования
  jsonplaceholder:
    base-url: https://jsonplaceholder.typicode.com
    timeout: 30s
    max-in-memory-size: 1MB

  # ReqRes - еще один тестовый API
  reqres:
    base-url: https://reqres.in
    timeout: 20s
    max-in-memory-size: 512KB

  # HTTP клиент общие настройки
  http-client:
    connect-timeout: 5s
    read-timeout: 30s
    write-timeout: 30s
    pool-size: 100

# Логирование
logging:
  level:
    org.gualsh.demo.httpe: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always