version: '3.1'
services:
  db:
    image: docker.io/library/postgres:16.3
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testbd
