# Single properties
#   spring.data.mongodb.uri="mongodb://admin:password@localhost:27017/baeldung"
#   шаблон - mongodb://<username>:<password>@<host>:<port>/<database>
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: user_db
      port: 27017
      host: localhost
      auto-index-creation: true # default false; авто создание индексов

# todo mongock section
mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean" # todo включаем при использовании spring-shell
  change-logs-scan-package:
    - ru.gulash.spring.mongock.changelog # todo где классы наката лежат
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: INFO
    # org.springframework.data.mongodb.core.MongoTemplate: DEBUG # логирует действия, связанные с взаимодействием Spring Data MongoDB
    # org.mongodb.driver.protocol.command: DEBUG # логирует низкоуровневые запросы MongoDB, такие как команды (например, find, insert, update, delete)
    # org.mongodb.driver: DEBUG # общий лог для драйвера MongoDB, который будет показывать все взаимодействия с сервером MongoDB, включая запросы и ответы
